name: yearn-v3-vault-periphery

plugins:
  - name: solidity
  - name: vyper
  - name: etherscan
  - name: hardhat

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    ref: 4.9.5
    
  - name: yearn-vaults
    github: yearn/yearn-vaults-v3
    ref: v3.0.2
    exclude: 
     - test/**/*
     
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.2
    contracts_folder: src
    exclude:
     - test/**/*

  - name: periphery
    github: yearn/tokenized-strategy-periphery
    ref: master
    contracts_folder: src
    exclude: 
     - test/**/*

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.9.5"
    - "@yearn-vaults=yearn-vaults/v3.0.2"
    - "@tokenized-strategy=tokenized-strategy/v3.0.2"
    - "@periphery=periphery/master"

ethereum:
  local:
    default_provider: hardhat
