name: yearn-v3-vault-periphery

plugins:
  - name: solidity
  - name: vyper
  - name: etherscan
  - name: hardhat
  - name: infura

default_ecosystem: ethereum

dependencies:
  - name: openzeppelin
    github: OpenZeppelin/openzeppelin-contracts
    version: 4.8.2
  - name: yearn-vaults
    github: yearn/yearn-vaults-v3
    ref: v3.0.1
  - name: tokenized-strategy
    github: yearn/tokenized-strategy
    ref: v3.0.1
    contracts_folder: src
    exclude:
     - src/test/**/*
  - name: periphery
    github: yearn/tokenized-strategy-periphery
    ref: master
    contracts_folder: src

solidity:
  import_remapping:
    - "@openzeppelin/contracts=openzeppelin/v4.8.2"
    - "@yearn-vaults=yearn-vaults/v3.0.1"
    - "@tokenized-strategy=tokenized-strategy/v3.0.1"
    - "@periphery=periphery/master"

ethereum:
  local:
    default_provider: hardhat